import java.awt.*;
import java.awt.Graphics;
import java.awt.event.*;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.border.*;

@SuppressWarnings("serial")
public class GUI extends javax.swing.JFrame implements Printable {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messagePane = new javax.swing.JOptionPane();
        bgPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        AddressBookTitle = new javax.swing.JLabel();
        AddressBookIcon = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        newPanel = new javax.swing.JPanel();
        btnNew = new javax.swing.JLabel();
        savePanel = new javax.swing.JPanel();
        btnSave = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JLabel();
        deletePanel = new javax.swing.JPanel();
        btnDelete = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        btnSearch = new javax.swing.JLabel();
        printPanel = new javax.swing.JPanel();
        btnPrint = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblAddress_1 = new javax.swing.JLabel();
        lblAddress_2 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblZipcode = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAddress_1 = new javax.swing.JTextField();
        txtAddress_2 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipcode = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();

        messagePane.setBackground(new java.awt.Color(245, 245, 245));
        messagePane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(245, 245, 245));

        sidePanel.setBackground(new java.awt.Color(153, 0, 28));

        AddressBookTitle.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        AddressBookTitle.setForeground(new java.awt.Color(240, 128, 128));
        AddressBookTitle.setText("Address Book");

        AddressBookIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressBookIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-address-book-400.png"))); // NOI18N

        menuPanel.setBackground(new java.awt.Color(133, 0, 28));

        newPanel.setBackground(new java.awt.Color(133, 0, 28));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Create_32px.png"))); // NOI18N
        btnNew.setToolTipText("New Address Entry");
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewMouseClicked(evt);
            }
        });

        savePanel.setBackground(new java.awt.Color(133, 0, 28));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_32px.png"))); // NOI18N
        btnSave.setToolTipText("Save Address Entry");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        updatePanel.setBackground(new java.awt.Color(133, 0, 28));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_Row_32px.png"))); // NOI18N
        btnUpdate.setToolTipText("Update Address Entry");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        deletePanel.setBackground(new java.awt.Color(133, 0, 28));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Trash_32px.png"))); // NOI18N
        btnDelete.setToolTipText("Delete Address Entry");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        searchPanel.setBackground(new java.awt.Color(133, 0, 28));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_View_32px.png"))); // NOI18N
        btnSearch.setToolTipText("Search Address Entry");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        printPanel.setBackground(new java.awt.Color(133, 0, 28));

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Print_32px.png"))); // NOI18N
        btnPrint.setToolTipText("Print Address Entry");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout printPanelLayout = new javax.swing.GroupLayout(printPanel);
        printPanel.setLayout(printPanelLayout);
        printPanelLayout.setHorizontalGroup(
            printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        printPanelLayout.setVerticalGroup(
            printPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(printPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdate)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addComponent(deletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout savePanelLayout = new javax.swing.GroupLayout(savePanel);
        savePanel.setLayout(savePanelLayout);
        savePanelLayout.setHorizontalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(savePanelLayout.createSequentialGroup()
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        savePanelLayout.setVerticalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout newPanelLayout = new javax.swing.GroupLayout(newPanel);
        newPanel.setLayout(newPanelLayout);
        newPanelLayout.setHorizontalGroup(
            newPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(newPanelLayout.createSequentialGroup()
                .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        newPanelLayout.setVerticalGroup(
            newPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(newPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(AddressBookTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddressBookIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(AddressBookTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressBookIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menuPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSeparator1.setBackground(new java.awt.Color(153, 0, 28));

        jSeparator2.setBackground(new java.awt.Color(153, 0, 28));

        jSeparator3.setBackground(new java.awt.Color(153, 0, 28));

        jSeparator4.setBackground(new java.awt.Color(153, 0, 28));

        jSeparator5.setBackground(new java.awt.Color(153, 0, 28));

        jSeparator6.setBackground(new java.awt.Color(153, 0, 28));

        jSeparator7.setBackground(new java.awt.Color(153, 0, 28));

        jSeparator8.setBackground(new java.awt.Color(153, 0, 28));

        jSeparator9.setBackground(new java.awt.Color(153, 0, 28));

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(153, 0, 28));
        lblFirstName.setText("First Name *");

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(153, 0, 28));
        lblLastName.setText("Last Name *");

        lblAddress_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAddress_1.setForeground(new java.awt.Color(153, 0, 28));
        lblAddress_1.setText("Address 1 *");

        lblAddress_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAddress_2.setForeground(new java.awt.Color(153, 0, 28));
        lblAddress_2.setText("Address 2");

        lblCity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCity.setForeground(new java.awt.Color(153, 0, 28));
        lblCity.setText("City *");

        lblState.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblState.setForeground(new java.awt.Color(153, 0, 28));
        lblState.setText("State *");

        lblZipcode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblZipcode.setForeground(new java.awt.Color(153, 0, 28));
        lblZipcode.setText("Zipcode *");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(153, 0, 28));
        lblPhone.setText("Phone *");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(153, 0, 28));
        lblEmail.setText("Email *");

        txtFirstName.setBackground(new java.awt.Color(245, 245, 245));
        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtFirstName.setForeground(new java.awt.Color(102, 102, 102));
        txtFirstName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtLastName.setBackground(new java.awt.Color(245, 245, 245));
        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(102, 102, 102));
        txtLastName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtAddress_1.setBackground(new java.awt.Color(245, 245, 245));
        txtAddress_1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtAddress_1.setForeground(new java.awt.Color(102, 102, 102));
        txtAddress_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtAddress_2.setBackground(new java.awt.Color(245, 245, 245));
        txtAddress_2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtAddress_2.setForeground(new java.awt.Color(102, 102, 102));
        txtAddress_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtCity.setBackground(new java.awt.Color(245, 245, 245));
        txtCity.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtCity.setForeground(new java.awt.Color(102, 102, 102));
        txtCity.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtState.setBackground(new java.awt.Color(245, 245, 245));
        txtState.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtState.setForeground(new java.awt.Color(102, 102, 102));
        txtState.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtZipcode.setBackground(new java.awt.Color(245, 245, 245));
        txtZipcode.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtZipcode.setForeground(new java.awt.Color(102, 102, 102));
        txtZipcode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtPhone.setBackground(new java.awt.Color(245, 245, 245));
        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(102, 102, 102));
        txtPhone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtEmail.setBackground(new java.awt.Color(245, 245, 245));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmail)
                    .addComponent(txtZipcode)
                    .addComponent(txtState)
                    .addComponent(txtAddress_1)
                    .addComponent(txtAddress_2)
                    .addComponent(txtLastName)
                    .addComponent(jSeparator8)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator7)
                    .addComponent(lblFirstName)
                    .addComponent(lblLastName)
                    .addComponent(lblAddress_1)
                    .addComponent(lblAddress_2)
                    .addComponent(lblCity)
                    .addComponent(lblState)
                    .addComponent(lblZipcode)
                    .addComponent(lblPhone)
                    .addComponent(jSeparator9)
                    .addComponent(lblEmail)
                    .addComponent(txtFirstName)
                    .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAddress_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAddress_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblZipcode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseClicked

        txtFirstName.setText("");
        txtLastName.setText("");
        txtAddress_1.setText("");
        txtAddress_2.setText("");
        txtCity.setText("");
        txtState.setText("");
        txtZipcode.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
    }//GEN-LAST:event_btnNewMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked

        if (txtFirstName.getText().equals("") || txtLastName.getText().equals("") || txtAddress_1.getText().equals("") || txtCity.getText().equals("") || txtState.getText().equals("") || txtZipcode.getText().equals("") || txtPhone.getText().equals("") || txtEmail.getText().equals(""))
        {
        	JOptionPane.showMessageDialog(messagePane, "Missing required fields!");
        }
        else if (txtPhone.getText().length() < 10 || txtPhone.getText().length() > 10)
        {
        	JOptionPane.showMessageDialog(messagePane, "Phone number must be 10 digits!");
        }
        else
        {
        	Queries Db = new Queries();
        	Db.insertQuery(txtFirstName.getText(), txtLastName.getText(), txtAddress_1.getText(), txtAddress_2.getText(), txtCity.getText(), txtState.getText(), txtZipcode.getText(), txtPhone.getText(), txtEmail.getText());
        }
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked

    	if (txtFirstName.getText().equals("") || txtLastName.getText().equals("") || txtAddress_1.getText().equals("") || txtCity.getText().equals("") || txtState.getText().equals("") || txtZipcode.getText().equals("") || txtPhone.getText().equals("") || txtEmail.getText().equals(""))
    	{
        	JOptionPane.showMessageDialog(messagePane, "Missing required fields!");
        }
        else if (txtPhone.getText().length() < 10 || txtPhone.getText().length() > 10)
        {
        	JOptionPane.showMessageDialog(messagePane, "Phone number must be 10 digits!");
        }
        else
        {
        	Queries Db = new Queries();
        	Db.updateQuery(txtFirstName.getText(), txtLastName.getText(), txtAddress_1.getText(), txtAddress_2.getText(), txtCity.getText(), txtState.getText(), txtZipcode.getText(), txtPhone.getText(), txtEmail.getText());
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked

    	if (!txtFirstName.getText().equals("") && !txtLastName.getText().equals("") && !txtPhone.getText().equals(""))
        {
    	Queries Db = new Queries();
        Db.deleteQuery(txtFirstName.getText(), txtLastName.getText(), txtPhone.getText());
        
        txtFirstName.setText("");
        txtLastName.setText("");
        txtAddress_1.setText("");
        txtAddress_2.setText("");
        txtCity.setText("");
        txtState.setText("");
        txtZipcode.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
    	
        boolean update = true;
    	
    	if (txtFirstName.getText().equals("") || txtLastName.getText().equals("") || txtPhone.getText().equals(""))
    	{
        	JOptionPane.showMessageDialog(messagePane, "Missing required fields!\nFirst name, last name, and phone number are required to search.");
        	
        	update = false;
        }
        else if (txtPhone.getText().length() < 10 || txtPhone.getText().length() > 10)
        {
        	JOptionPane.showMessageDialog(messagePane, "Phone number must be 10 digits!");
        	
        	update = false;
        }
        else
        {
        Queries Db = new Queries();
        Db.searchQuery(txtFirstName.getText(), txtLastName.getText(), txtPhone.getText()); 
        }

		if (fName == null && update)
		{
    		JOptionPane.showMessageDialog(messagePane, "Record not found!");
    		update = false;
		}
        
    	if (update)
    	{
    		txtFirstName.setText(fName);
    		txtFirstName.validate();
    		txtLastName.setText(lName);
    		txtLastName.validate();
    		txtAddress_1.setText(address1);
    		txtAddress_1.validate();
    		txtAddress_2.setText(address2);
    		txtCity.setText(city1);
    		txtState.setText(state1);
    		txtZipcode.setText(zipcode1);
    		txtPhone.setText(phone);
    		txtEmail.setText(email);
    	}
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked

            PrinterJob job = PrinterJob.getPrinterJob();

            job.setPrintable(this);

            boolean ok = job.printDialog();

            if (ok) {

                try
                {
                    job.print();
                }

                catch (PrinterException ex)
                {
                    JOptionPane.showMessageDialog( null, ex.getMessage(), "Print Error", JOptionPane.ERROR_MESSAGE );
                }
            }
    }//GEN-LAST:event_btnPrintMouseClicked

    public void updateFields(String firstName, String lastName, String address_1, String address_2, String city, String state, String zipcode, String phoneNumber, String emailAddress) {

    	fName = firstName;
    	lName = lastName;
    	address1 = address_1;
    	address2 = address_2;
    	city1 = city;
    	state1 = state;
    	zipcode1 = zipcode;
    	phone = phoneNumber;
    	email = emailAddress;
	}

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {

        if (pageIndex > 0)
        {
            return NO_SUCH_PAGE;
        }

        Graphics2D g2d = (Graphics2D) graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

        bgPanel.printAll(graphics);

        return PAGE_EXISTS;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressBookIcon;
    private javax.swing.JLabel AddressBookTitle;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel btnNew;
    private javax.swing.JLabel btnPrint;
    private javax.swing.JLabel btnSave;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAddress_1;
    private javax.swing.JLabel lblAddress_2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblZipcode;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel newPanel;
    private javax.swing.JPanel printPanel;
    private javax.swing.JPanel savePanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField txtAddress_1;
    private javax.swing.JTextField txtAddress_2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZipcode;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables
    private static String fName, lName, address1, address2, city1, state1, zipcode1, phone, email;
    public JOptionPane messagePane;
}